paths:
  "/api/atlas/v2/groups/{groupId}/clusters":
    post:
      summary: TEST DESCRIPTION
      x-watcher-state: IDLE
      x-watcher-operation: getCluster
      x-watcher-description: WATCH DESCRIPTION
      x-watcher-timeout-description: WATCH TIMEOUT DESCRIPTION
      x-watcher-return-property: StateName
      x-watcher-params:
        - key: GroupId
          value: GroupId
        - key: ClusterName
          value: Name
components:
  parameters:
    groupId:
      description: Unique 24-hexadecimal digit string that identifies your project.
      x-group-id: true
      x-flag-name: projectId
    orgId:
      description: Unique 24-hexadecimal digit string that identifies the organization
      x-org-id: true
