generatorName: go
gitUserId: mongodb
gitRepoId: mongodb-atlas-cli
gitHost: github.com
templateDir: config/go-templates
isGoSubmodule: true
packageName: api
inputSpec: config/atlas-api-transformed.yaml
files:
  cmd.mustache:
    templateType: API
    destinationFilename: _cmd.go
  api.mustache:
    destinationFilename: api.go
    templateType: SupportingFiles
  client.mustache:
    destinationFilename: client.go
    templateType: SupportingFiles
